name: qr_scanner_web
description: QR Scanner for WEB.
version: 0.0.3-beta-1
homepage: https://github.com/hmbenhaim/qr_scanner_web

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter    
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: QrScannerWeb
        fileName: qr_scanner_web.dart


